name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v30

    - name: Restore and save Nix store
      uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-store
        restore-prefixes-first-match: nix-store
        # Collect garbage until store is at most 2GB before saving cache
        gc-max-store-size: 2G

    - name: Run all checks
      run: nix run .#checklist-all -- -v 